import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PDFData {
  title: string;
  subtitle: string;
  oldForm: string;
  newForm: string;
  content: string;
}

const PRIMARY_GREEN: [number, number, number] = [22, 101, 52];
const ACCENT_GREEN: [number, number, number] = [16, 185, 129];
const AMBER: [number, number, number] = [217, 119, 6];
const RED: [number, number, number] = [220, 38, 38];
const GREEN: [number, number, number] = [22, 163, 74];

const clean = (s: string) => s
  .replace(/\*\*(.*?)\*\*/g, '$1')
  .replace(/\*(.*?)\*/g, '$1')
  .replace(/[₹¹â‚¹\u20B9]/g, 'Rs.')
  .replace(/→|➜|➡/g, '->')
  .replace(/←/g, '<-')
  .replace(/↓|↕/g, ' | ')
  .replace(/[^\x20-\x7E]/g, '');

const preProcess = (line: string) => {
  return line
    .replace(/^\s*(>+\s*)+/, '').trimStart()
    .replace(/^#{1,4}\s*/, '') // strip markdown heading prefixes (### SECTION -> SECTION)
    .replace(/^[\s%]+$/gm, '')
    .replace(/\*?\[?NEEDS EXPERT REVIEW[^\]*\n]*[\]*]?/gi, '[NEEDS EXPERT REVIEW]')
    .replace(/<strike>(.*?)<\/strike>/gi, '[DEL: $1]')
    .replace(/<s>(.*?)<\/s>/gi, '[DEL: $1]')
    .replace(/<u>(.*?)<\/u>/gi, '[ADD: $1]')
    .replace(/<ins>(.*?)<\/ins>/gi, '[ADD: $1]')
    .replace(/<[^>]+>/g, '');
};

export function generateAnalysisPDF(data: PDFData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let cursorY = 0;
  let justStartedSection = false;
  let currentSectionLabel = '';

  // Helper for footer
  const addFooter = () => {
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      if (i === 1) {
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text("Cover", pageWidth / 2, pageHeight - 10, { align: "center" });
        continue;
      }
      doc.setDrawColor(200);
      doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.text("TaxDiff Analyst | Confidential", margin, pageHeight - 10);
      doc.text(`${data.oldForm} -> ${data.newForm}`, pageWidth / 2, pageHeight - 10, { align: "center" });
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: "right" });
    }
  };

  // Page 1: Cover
  doc.setFillColor(PRIMARY_GREEN[0], PRIMARY_GREEN[1], PRIMARY_GREEN[2]);
  doc.rect(0, 0, pageWidth, 50, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("TaxDiff Legal Analysis Report", margin, 32);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Income Tax Act 1961 -> New Income Tax Act 2025", margin, 42);

  cursorY = 70;
  doc.setTextColor(0, 0, 0);
  doc.setDrawColor(230);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, cursorY, pageWidth - margin * 2, 70, 5, 5, 'FD');
  
  const cardCenterX = pageWidth / 2;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(100, 100, 100);
  doc.text("COMPARATIVE ANALYSIS", cardCenterX, cursorY + 13, { align: "center" });

  doc.setDrawColor(200);
  doc.line(margin + 15, cursorY + 17, pageWidth - margin - 15, cursorY + 17);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PRIMARY_GREEN[0], PRIMARY_GREEN[1], PRIMARY_GREEN[2]);
  doc.text(data.oldForm, cardCenterX, cursorY + 30, { align: "center" });

  // Teal triangle arrow + horizontal rules
  const ax = cardCenterX;
  const ay = cursorY + 37;
  doc.setFillColor(ACCENT_GREEN[0], ACCENT_GREEN[1], ACCENT_GREEN[2]);
  doc.triangle(ax - 8, ay, ax + 8, ay, ax, ay + 7, 'F');
  doc.setDrawColor(ACCENT_GREEN[0], ACCENT_GREEN[1], ACCENT_GREEN[2]);
  doc.setLineWidth(0.5);
  doc.line(margin + 15, ay + 3, ax - 11, ay + 3);
  doc.line(ax + 11, ay + 3, pageWidth - margin - 15, ay + 3);
  doc.setLineWidth(0.2);

  doc.setFontSize(14);
  doc.setTextColor(ACCENT_GREEN[0], ACCENT_GREEN[1], ACCENT_GREEN[2]);
  doc.text(data.newForm, cardCenterX, cursorY + 53, { align: "center" });

  cursorY += 80;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated Date: ${new Date().toLocaleDateString()}`, margin, cursorY);
  doc.text("Prepared by: TaxDiff Analyst", margin, cursorY + 6);

  cursorY += 20;
  doc.setFillColor(255, 251, 235);
  doc.setDrawColor(251, 191, 36);
  doc.roundedRect(margin, cursorY, pageWidth - margin * 2, 30, 3, 3, 'FD');
  doc.setTextColor(146, 64, 14);
  doc.setFontSize(9);
  doc.text("DISCLAIMER: This report is generated by AI and intended for professional guidance only.", margin + 5, cursorY + 10);
  doc.text("It does not constitute legal advice. Please verify all findings with official gazette notifications.", margin + 5, cursorY + 18);

  // Page 2: Table of Contents
  doc.addPage();
  cursorY = 30;
  doc.setTextColor(PRIMARY_GREEN[0], PRIMARY_GREEN[1], PRIMARY_GREEN[2]);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Contents", margin, cursorY);
  
  cursorY += 15;
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  const tocItems = [
    { label: '1. Form Identity Card',              page: 3 },
    { label: '2. Track Changes (Redline)',          page: 4 },
    { label: '3. Categorised Change Analysis',      page: 5 },
    { label: '4. IT System & Record-Keeping Impact', page: 6 },
    { label: '5. Risk Flags for Tax Professionals',  page: 7 },
    { label: '6. Executive Summary',                page: 8 },
  ];
  tocItems.forEach((item) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0,0,0);
    
    // Draw label
    doc.text(item.label, margin, cursorY);
    const labelW = doc.getTextWidth(item.label);
    
    // Draw page number (right-aligned)
    const pageStr = item.page.toString();
    const pageW = doc.getTextWidth(pageStr);
    doc.text(pageStr, pageWidth - margin, cursorY, { align: 'right' });
    
    // Fill gap with dots
    const dotW = doc.getTextWidth('.');
    const gapStart = margin + labelW + 4;
    const gapEnd = pageWidth - margin - pageW - 4;
    doc.setTextColor(180,180,180);
    doc.setFontSize(9);
    let dotX = gapStart;
    while (dotX + dotW < gapEnd) {
      doc.text('.', dotX, cursorY);
      dotX += dotW + 1;
    }
    doc.setTextColor(0,0,0);
    cursorY += 9;
  });

  cursorY += 10;
  doc.setFontSize(12);
  doc.text("Track Change Legend", margin, cursorY);
  cursorY += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  doc.setTextColor(RED[0], RED[1], RED[2]);
  doc.text("deleted text", margin, cursorY);
  const textWidth = doc.getTextWidth("deleted text");
  doc.setDrawColor(RED[0], RED[1], RED[2]);
  doc.line(margin, cursorY - 3, margin + textWidth, cursorY - 3);
  
  cursorY += 6;
  doc.setTextColor(GREEN[0], GREEN[1], GREEN[2]);
  doc.text("added text", margin, cursorY);
  const textWidth2 = doc.getTextWidth("added text");
  doc.setDrawColor(GREEN[0], GREEN[1], GREEN[2]);
  doc.line(margin, cursorY + 1.5, margin + textWidth2, cursorY + 1.5);
  
  cursorY += 6;
  doc.setTextColor(AMBER[0], AMBER[1], AMBER[2]);
  doc.setFont("helvetica", "bold");
  doc.text("[NEEDS EXPERT REVIEW]", margin, cursorY);
  
  cursorY += 15;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text("Category Badge Legend", margin, cursorY);
  cursorY += 10;
  const categories = [
    ["[A]", "Scope Enlargement"], ["[B]", "Scope Reduction"],
    ["[C]", "New Info Required"], ["[D]", "Information Removed"],
    ["[E]", "Threshold/Numerical"], ["[F]", "Language Change"],
    ["[G]", "Renumbering"], ["[H]", "Procedural"],
    ["[I]", "System/Digital"], ["[J]", "Structural Reorg"],
    ["[K]", "New Obligation"], ["[L]", "Obligation Removed"]
  ];
  
  const catBadgeColors: Record<string, [number,number,number]> = {
    '[A]': [22,101,52],  '[B]': [153,27,27],  '[C]': [30,64,175],
    '[D]': [154,52,18],  '[E]': [107,33,168], '[F]': [17,94,89],
    '[G]': [75,85,99],   '[H]': [146,64,14],  '[I]': [12,74,110],
    '[J]': [55,48,163],  '[K]': [153,27,27],  '[L]': [20,83,45],
  };
  const catBadgeBg: Record<string, [number,number,number]> = {
    '[A]': [220,252,231], '[B]': [254,226,226], '[C]': [219,234,254],
    '[D]': [255,237,213], '[E]': [243,232,255], '[F]': [204,251,241],
    '[G]': [243,244,246], '[H]': [254,243,199], '[I]': [224,242,254],
    '[J]': [238,242,255], '[K]': [254,215,215], '[L]': [187,247,208],
  };

  categories.forEach((cat, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = margin + col * 85;
    const y = cursorY + row * 9;
    const bg = catBadgeBg[cat[0]] || [240,240,240];
    const fg = catBadgeColors[cat[0]] || [0,0,0];
    
    doc.setFillColor(bg[0], bg[1], bg[2]);
    doc.roundedRect(x, y - 4, 13, 6, 1, 1, 'F');
    doc.setFontSize(7); doc.setFont('helvetica','bold');
    doc.setTextColor(fg[0], fg[1], fg[2]);
    doc.text(cat[0].replace(/[[\]]/g,''), x + 2, y);
    
    doc.setFontSize(8); doc.setFont('helvetica','normal');
    doc.setTextColor(50,50,50);
    doc.text(cat[1], x + 15, y);
  });

  // Content Sections
  const lines = data.content.split('\n');
  let currentSection = 0;

  const renderTaggedLine = (line: string, y: number, indent = 0): number => {
    const segments = line.split(/(\[DEL:.*?\]|\[ADD:.*?\]|\[NEEDS EXPERT REVIEW\]|\[NEW CLAUSE\]|\[REMOVED CLAUSE\])/g);
    let currentX = margin + indent;
    let currentY = y;
    const maxWidth = pageWidth - margin * 2;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    segments.forEach(seg => {
      if (!seg) return;

      let color = [26, 26, 26];
      let style = "normal";
      let decoration: 'strike' | 'underline' | 'pill' | 'none' = 'none';
      let pillColor = [240, 240, 240];
      let text = seg;

      if (seg.startsWith('[DEL:')) {
        color = RED;
        decoration = 'strike';
        text = seg.substring(5, seg.length - 1);
      } else if (seg.startsWith('[ADD:')) {
        color = GREEN;
        decoration = 'underline';
        text = seg.substring(5, seg.length - 1);
      } else if (seg === '[NEEDS EXPERT REVIEW]') {
        color = AMBER;
        style = "bold";
      } else if (seg === '[NEW CLAUSE]') {
        color = [255, 255, 255];
        pillColor = GREEN;
        decoration = 'pill';
      } else if (seg === '[REMOVED CLAUSE]') {
        color = [255, 255, 255];
        pillColor = RED;
        decoration = 'pill';
      }

      doc.setFont("helvetica", style);
      doc.setTextColor(color[0], color[1], color[2]);

      const words = text.split(' ');
      words.forEach((word, idx) => {
        const wordText = word + (idx === words.length - 1 ? "" : " ");
        const wordWidth = doc.getTextWidth(wordText);

        if (currentX + wordWidth > maxWidth) {
          currentX = margin + indent;
          currentY += 6;
          if (currentY > pageHeight - 30) {
            doc.addPage();
            currentY = 25;
            if (justStartedSection) {
              justStartedSection = false;
            } else {
              doc.setFontSize(8);
              doc.setTextColor(150, 150, 150);
              doc.text(currentSectionLabel + ' continued...', margin, 15);
            }
            doc.setFontSize(10);
            doc.setTextColor(color[0], color[1], color[2]);
          }
        }

        if (decoration === 'pill') {
          doc.setFillColor(pillColor[0], pillColor[1], pillColor[2]);
          doc.roundedRect(currentX - 1, currentY - 4, wordWidth + 2, 6, 1, 1, 'F');
        }

        doc.text(wordText, currentX, currentY);

        if (decoration === 'strike') {
          doc.setDrawColor(color[0], color[1], color[2]);
          doc.line(currentX, currentY - 1, currentX + wordWidth, currentY - 1);
        } else if (decoration === 'underline') {
          doc.setDrawColor(color[0], color[1], color[2]);
          doc.line(currentX, currentY + 1, currentX + wordWidth, currentY + 1);
        }

        currentX += wordWidth;
      });
    });

    return currentY + 6;
  };

  // Helper: Draw cell content with [DEL:]/[ADD:] inline coloring
  const drawTaggedCell = (doc: jsPDF, cell: any, text: string) => {
    const segments = text.split(/(\[DEL:.*?\]|\[ADD:.*?\]|\[NEW CLAUSE\]|\[REMOVED CLAUSE\])/g);
    const cellX = cell.x + cell.padding('left');
    const cellW = cell.width - cell.padding('left') - cell.padding('right');
    let curX = cellX;
    let curY = cell.y + cell.padding('top') + 3.5;
    
    doc.setFontSize(8);
    
    segments.forEach((seg: string) => {
      if (!seg) return;
      
      let color: number[] = [30, 30, 30];
      let isStrike = false;
      let isUnderline = false;
      let displayText = seg;
      
      if (seg.startsWith('[DEL:')) {
        color = [220, 38, 38]; // RED
        isStrike = true;
        displayText = seg.substring(5, seg.length - 1).trim();
      } else if (seg.startsWith('[ADD:')) {
        color = [22, 163, 74]; // GREEN
        isUnderline = true;
        displayText = seg.substring(5, seg.length - 1).trim();
      } else if (seg === '[NEW CLAUSE]') {
        color = [22, 163, 74];
        displayText = '[NEW CLAUSE] ';
        doc.setFont('helvetica', 'bold');
      } else if (seg === '[REMOVED CLAUSE]') {
        color = [220, 38, 38];
        displayText = '[REMOVED] ';
        doc.setFont('helvetica', 'bold');
      }
      
      doc.setTextColor(color[0], color[1], color[2]);
      
      const words = displayText.split(' ');
      words.forEach((word: string, idx: number) => {
        const w = word + (idx < words.length - 1 ? ' ' : '');
        const wWidth = doc.getTextWidth(w);
        
        if (curX + wWidth > cellX + cellW) {
          curX = cellX;
          curY += 4;
        }
        
        doc.text(w, curX, curY);
        
        if (isStrike) {
          doc.setDrawColor(color[0], color[1], color[2]);
          doc.setLineWidth(0.3);
          doc.line(curX, curY - 1, curX + wWidth - 1, curY - 1);
        }
        if (isUnderline) {
          doc.setDrawColor(color[0], color[1], color[2]);
          doc.setLineWidth(0.3);
          doc.line(curX, curY + 1, curX + wWidth - 1, curY + 1);
        }
        
        curX += wWidth;
      });
      
      // Reset font after bold tags
      doc.setFont('helvetica', 'normal');
    });
    
    doc.setTextColor(0, 0, 0);
    doc.setLineWidth(0.2);
  };

  // Check if text contains track change tags
  const hasTrackChangeTags = (text: string) => /\[(DEL|ADD|NEW CLAUSE|REMOVED CLAUSE)/.test(text);

  // Main processing loop
  let inTable = false;
  let tableRows: any[] = [];
  let tableHeaders: any[] = [];

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = clean(preProcess(rawLine));
    if (!line.trim() || line === '---') continue;

    const isSectionHeader = (line.startsWith('SECTION') || 
      (line.includes('SECTION') && line.includes('—')));
    
    // Detect sub-section headers (e.g., SECTION 2A, SECTION 2B)
    const isSubSectionHeader = /^SECTION\s+\d+[A-Z]/i.test(line);

    if (isSectionHeader && !isSubSectionHeader) {
      // Flush table if we were in one
      if (inTable && tableHeaders.length > 0) {
        if (cursorY + 20 > pageHeight - 30) {
          doc.addPage();
          cursorY = 25;
        }
        autoTable(doc, {
          startY: cursorY,
          head: [tableHeaders],
          body: tableRows,
          margin: { left: margin, right: margin },
          styles: { fontSize: 8, cellPadding: 3, lineColor: [200,220,210] },
          headStyles: {
            fillColor: PRIMARY_GREEN,
            textColor: [255,255,255],
            fontStyle: 'bold',
            fontSize: 9
          },
          alternateRowStyles: { fillColor: [248,250,248] },
          columnStyles: currentSection === 2 ? (tableHeaders.length === 3 ? {
            0: { cellWidth: 12 },
            1: { cellWidth: 79 },
            2: { cellWidth: 79 }
          } : {
            0: { cellWidth: 28 },
            1: { cellWidth: 47 },
            2: { cellWidth: 47 },
            3: { cellWidth: 48 }
          }) : currentSection === 3 ? {
            0: { cellWidth: 8 },
            1: { cellWidth: 25 },
            2: { cellWidth: 45 },
            3: { cellWidth: 25 },
            4: { cellWidth: 25 },
            5: { cellWidth: 42 }
          } : currentSection === 4 ? {
            0: { cellWidth: 8 },
            1: { cellWidth: 28 },
            2: { cellWidth: 35 },
            3: { cellWidth: 28 },
            4: { cellWidth: 71 }
          } : {},

          willDrawCell: (data: any) => {
            if (data.section !== 'body' || !data.cell.raw) return;
            const val = String(data.cell.raw);
            if (currentSection === 2 && hasTrackChangeTags(val)) {
              // Clear default text rendering
              data.cell.text = [''];
            }
          },
          didDrawCell: (data: any) => {
            if (data.section !== 'body' || !data.cell.raw) return;
            const val = String(data.cell.raw).replace(/\*\*(.*?)\*\*/g, '$1');
            if (currentSection === 2 && hasTrackChangeTags(val)) {
              drawTaggedCell(doc, data.cell, val);
            }
          },
          didParseCell: (data: any) => {
            if (!data.cell.raw) return;
            const val = String(data.cell.raw);
            data.cell.text = [val.replace(/\*\*(.*?)\*\*/g, '$1')];
            
            if (currentSection === 3 && data.section === 'body' &&
                (data.column.index === 3 || data.column.index === 4)) {
              
              const catStyles: Record<string, { bg: [number,number,number], text: [number,number,number] }> = {
                'A': { bg: [220, 252, 231], text: [22, 101, 52] },
                'B': { bg: [254, 226, 226], text: [153, 27, 27] },
                'C': { bg: [219, 234, 254], text: [30, 64, 175] },
                'D': { bg: [255, 237, 213], text: [154, 52, 18] },
                'E': { bg: [243, 232, 255], text: [107, 33, 168] },
                'F': { bg: [204, 251, 241], text: [17, 94, 89] },
                'G': { bg: [243, 244, 246], text: [75, 85, 99] },
                'H': { bg: [254, 243, 199], text: [146, 64, 14] },
                'I': { bg: [224, 242, 254], text: [12, 74, 110] },
                'J': { bg: [238, 242, 255], text: [55, 48, 163] },
                'K': { bg: [254, 226, 226], text: [153, 27, 27] },
                'L': { bg: [220, 252, 231], text: [22, 101, 52] },
              };

              const match = val.match(/\[([A-L])\]/);
              let catKey = match?.[1] || null;
              
              if (!catKey) {
                const lower = val.toLowerCase();
                if (lower.includes('scope enlargement') || lower.includes('scope expansion')) catKey = 'A';
                else if (lower.includes('scope reduction')) catKey = 'B';
                else if (lower.includes('new info') || lower.includes('new information')) catKey = 'C';
                else if (lower.includes('information removed') || lower.includes('info removed')) catKey = 'D';
                else if (lower.includes('threshold') || lower.includes('numerical')) catKey = 'E';
                else if (lower.includes('language') || lower.includes('terminology')) catKey = 'F';
                else if (lower.includes('renumbering') || lower.includes('statutory') || lower.includes('section/rule')) catKey = 'G';
                else if (lower.includes('procedural') || lower.includes('process')) catKey = 'H';
                else if (lower.includes('system') || lower.includes('digital')) catKey = 'I';
                else if (lower.includes('structural') || lower.includes('reorganis')) catKey = 'J';
                else if (lower.includes('new compliance') || lower.includes('new obligation') || lower.includes('compliance obligation') || lower.includes('new form') || lower.includes('audit') || lower.includes('verification')) catKey = 'K';
                else if (lower.includes('obligation removed') || lower.includes('removed obligation')) catKey = 'L';
              }
              
              if (catKey) {
                const style = catStyles[catKey];
                if (style) {
                  data.cell.styles.fillColor = style.bg;
                  data.cell.styles.textColor = style.text;
                  data.cell.styles.fontStyle = 'bold';
                }
              }
            }
          }
        });
        cursorY = (doc as any).previousAutoTable.finalY + 10;
        inTable = false;
        tableRows = [];
        tableHeaders = [];
      }

      doc.addPage();
      cursorY = 20;

      currentSectionLabel = clean(line).replace(/^#+\s*/, '').trim();

      doc.setFillColor(16, 185, 129);
      doc.rect(0, cursorY, pageWidth, 14, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(currentSectionLabel, margin, cursorY + 9);
      cursorY += 20;

      if (line.includes('SECTION 1') || line.includes('IDENTITY CARD')) currentSection = 1;
      if (line.includes('SECTION 2') || line.includes('TRACK CHANGES')) currentSection = 2;
      if (line.includes('SECTION 3') || line.includes('CATEGORISED')) currentSection = 3;
      if (line.includes('SECTION 4') || line.includes('IT SYSTEM')) currentSection = 4;
      if (line.includes('SECTION 5') || line.includes('RISK FLAG')) currentSection = 5;
      if (line.includes('SECTION 6') || line.includes('EXECUTIVE SUMMARY')) {
        currentSection = 6;
      }

      justStartedSection = true;
      continue;
    }

    // Sub-section headers (e.g., SECTION 2A: CHANGES IN RULE)
    if (isSubSectionHeader) {
      // Flush table if we were in one
      if (inTable && tableHeaders.length > 0) {
        if (cursorY + 20 > pageHeight - 30) {
          doc.addPage();
          cursorY = 25;
        }
        autoTable(doc, {
          startY: cursorY,
          head: [tableHeaders],
          body: tableRows,
          margin: { left: margin, right: margin },
          styles: { fontSize: 8, cellPadding: 3, lineColor: [200,220,210] },
          headStyles: {
            fillColor: PRIMARY_GREEN,
            textColor: [255,255,255],
            fontStyle: 'bold',
            fontSize: 9
          },
          alternateRowStyles: { fillColor: [248,250,248] },
          columnStyles: currentSection === 2 ? (tableHeaders.length === 3 ? {
            0: { cellWidth: 12 },
            1: { cellWidth: 79 },
            2: { cellWidth: 79 }
          } : {
            0: { cellWidth: 28 },
            1: { cellWidth: 47 },
            2: { cellWidth: 47 },
            3: { cellWidth: 48 }
          }) : currentSection === 3 ? {
            0: { cellWidth: 8 },
            1: { cellWidth: 25 },
            2: { cellWidth: 45 },
            3: { cellWidth: 25 },
            4: { cellWidth: 25 },
            5: { cellWidth: 42 }
          } : currentSection === 4 ? {
            0: { cellWidth: 8 },
            1: { cellWidth: 28 },
            2: { cellWidth: 35 },
            3: { cellWidth: 28 },
            4: { cellWidth: 71 }
          } : {},

          willDrawCell: (data: any) => {
            if (data.section !== 'body' || !data.cell.raw) return;
            const val = String(data.cell.raw);
            if (currentSection === 2 && hasTrackChangeTags(val)) {
              // Clear default text rendering
              data.cell.text = [''];
            }
          },
          didDrawCell: (data: any) => {
            if (data.section !== 'body' || !data.cell.raw) return;
            const val = String(data.cell.raw).replace(/\*\*(.*?)\*\*/g, '$1');
            if (currentSection === 2 && hasTrackChangeTags(val)) {
              drawTaggedCell(doc, data.cell, val);
            }
          },
          didParseCell: (data: any) => {
            if (!data.cell.raw) return;
            const val = String(data.cell.raw);
            data.cell.text = [val.replace(/\*\*(.*?)\*\*/g, '$1')];
          }
        });
        cursorY = (doc as any).previousAutoTable.finalY + 10;
        inTable = false;
        tableRows = [];
        tableHeaders = [];
      }

      const subLabel = clean(line).replace(/^#+\s*/, '').trim();
      
      // Force new page for SECTION 2B (Changes in Form)
      if (/2B/i.test(line)) {
        doc.addPage();
        cursorY = 25;
      } else if (cursorY + 25 > pageHeight - 30) {
        doc.addPage();
        cursorY = 25;
      }

      cursorY += 6;
      doc.setFillColor(240, 253, 244); // light green bg
      doc.setDrawColor(16, 185, 129);  // green border
      doc.roundedRect(margin, cursorY - 5, pageWidth - margin * 2, 12, 2, 2, 'FD');
      doc.setTextColor(22, 101, 52);   // dark green text
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(subLabel, margin + 5, cursorY + 3);
      cursorY += 14;
      continue;
    }

    // Table handling
    if (line.startsWith('|')) {
      // Skip pure separator rows (e.g. |---|---|)
      if (/^[ \-|:]+$/.test(line)) continue;
      
      const cells = line.split('|')
        .filter(c => c.trim() !== '')
        .map(c => c.trim().replace(/\*\*(.*?)\*\*/g, '$1'));
      
      if (!inTable) {
        inTable = true;
        tableHeaders = cells;
        tableRows = [];
      } else {
        tableRows.push(cells);
      }
      continue;
    }
    
    // Flush table when a non-pipe line is encountered
    if (inTable) {
      if (tableHeaders.length > 0) {
        if (cursorY + 20 > pageHeight - 30) {
          doc.addPage();
          cursorY = 25;
        }
        autoTable(doc, {
          startY: cursorY,
          head: [tableHeaders],
          body: tableRows,
          margin: { left: margin, right: margin },
          styles: { fontSize: 8, cellPadding: 3, lineColor: [200,220,210] },
          headStyles: {
            fillColor: PRIMARY_GREEN,
            textColor: [255,255,255],
            fontStyle: 'bold',
            fontSize: 9
          },
          alternateRowStyles: { fillColor: [248,250,248] },
          columnStyles: currentSection === 2 ? (tableHeaders.length === 3 ? {
            0: { cellWidth: 12 },
            1: { cellWidth: 79 },
            2: { cellWidth: 79 }
          } : {
            0: { cellWidth: 28 },
            1: { cellWidth: 47 },
            2: { cellWidth: 47 },
            3: { cellWidth: 48 }
          }) : currentSection === 3 ? {
            0: { cellWidth: 8 },
            1: { cellWidth: 25 },
            2: { cellWidth: 45 },
            3: { cellWidth: 25 },
            4: { cellWidth: 25 },
            5: { cellWidth: 42 }
          } : currentSection === 4 ? {
            0: { cellWidth: 8 },
            1: { cellWidth: 28 },
            2: { cellWidth: 35 },
            3: { cellWidth: 28 },
            4: { cellWidth: 71 }
          } : {},

          willDrawCell: (data: any) => {
            if (data.section !== 'body' || !data.cell.raw) return;
            const val = String(data.cell.raw);
            if (currentSection === 2 && hasTrackChangeTags(val)) {
              // Clear default text rendering
              data.cell.text = [''];
            }
          },
          didDrawCell: (data: any) => {
            if (data.section !== 'body' || !data.cell.raw) return;
            const val = String(data.cell.raw).replace(/\*\*(.*?)\*\*/g, '$1');
            if (currentSection === 2 && hasTrackChangeTags(val)) {
              drawTaggedCell(doc, data.cell, val);
            }
          },
          didParseCell: (data: any) => {
            if (!data.cell.raw) return;
            const val = String(data.cell.raw);
            // Strip bold markers
            data.cell.text = [val.replace(/\*\*(.*?)\*\*/g, '$1')];
            
            // Colour category columns in Section 3
            if (currentSection === 3 && data.section === 'body' &&
                (data.column.index === 3 || data.column.index === 4)) {
              
              const catStyles: Record<string, { bg: [number,number,number], text: [number,number,number] }> = {
                'A': { bg: [220, 252, 231], text: [22, 101, 52] },   // Scope Enlargement - Green
                'B': { bg: [254, 226, 226], text: [153, 27, 27] },  // Scope Reduction - Red
                'C': { bg: [219, 234, 254], text: [30, 64, 175] },  // New Info Required - Blue
                'D': { bg: [255, 237, 213], text: [154, 52, 18] },  // Information Removed - Orange
                'E': { bg: [243, 232, 255], text: [107, 33, 168] }, // Threshold/Numerical - Purple
                'F': { bg: [204, 251, 241], text: [17, 94, 89] },   // Language Change - Teal
                'G': { bg: [243, 244, 246], text: [75, 85, 99] },   // Renumbering - Grey
                'H': { bg: [254, 243, 199], text: [146, 64, 14] },  // Procedural - Amber
                'I': { bg: [224, 242, 254], text: [12, 74, 110] },  // System/Digital - Light Blue
                'J': { bg: [238, 242, 255], text: [55, 48, 163] },  // Structural Reorg - Indigo
                'K': { bg: [254, 226, 226], text: [153, 27, 27] },  // New Obligation - Red
                'L': { bg: [220, 252, 231], text: [22, 101, 52] },  // Obligation Removed - Green
              };

              const match = val.match(/\[([A-L])\]/);
              let catKey = match?.[1] || null;
              
              // Fallback: match by keyword if no letter code found
              if (!catKey) {
                const lower = val.toLowerCase();
                if (lower.includes('scope enlargement') || lower.includes('scope expansion')) catKey = 'A';
                else if (lower.includes('scope reduction')) catKey = 'B';
                else if (lower.includes('new info') || lower.includes('new information')) catKey = 'C';
                else if (lower.includes('information removed') || lower.includes('info removed')) catKey = 'D';
                else if (lower.includes('threshold') || lower.includes('numerical')) catKey = 'E';
                else if (lower.includes('language') || lower.includes('terminology')) catKey = 'F';
                else if (lower.includes('renumbering') || lower.includes('statutory') || lower.includes('section/rule')) catKey = 'G';
                else if (lower.includes('procedural') || lower.includes('process')) catKey = 'H';
                else if (lower.includes('system') || lower.includes('digital')) catKey = 'I';
                else if (lower.includes('structural') || lower.includes('reorganis')) catKey = 'J';
                else if (lower.includes('new compliance') || lower.includes('new obligation') || lower.includes('compliance obligation') || lower.includes('new form') || lower.includes('audit') || lower.includes('verification')) catKey = 'K';
                else if (lower.includes('obligation removed') || lower.includes('removed obligation')) catKey = 'L';
              }
              
              if (catKey) {
                const style = catStyles[catKey];
                if (style) {
                  data.cell.styles.fillColor = style.bg;
                  data.cell.styles.textColor = style.text;
                  data.cell.styles.fontStyle = 'bold';
                }
              }
            }
          }
        });
        cursorY = (doc as any).previousAutoTable.finalY + 10;
      }
      inTable = false;
      tableRows = [];
      tableHeaders = [];
    }

    // Section 4 is now rendered as a table (handled by the generic table handler above)

    const isRiskLine = (currentSection === 5 && (
      line.startsWith("-") || 
      line.startsWith("*") || 
      /^(High|Medium|Low|Data Matching|Risk)\s*Risk/i.test(line)
    ));

    if (isRiskLine) {
      const riskText = line.replace(/^[-*•]\s*/, '');
      const boldMatch = riskText.match(/\*\*(.*?)\*\*/);
      const colonIdx = riskText.indexOf(':');
      
      let riskTitle: string;
      let riskBody: string;

      if (boldMatch) {
        riskTitle = boldMatch[1];
        riskBody = riskText.replace(/\*\*(.*?)\*\*:?\s*/, '').replace(/\*(.*?)\*/g, '$1');
      } else if (colonIdx !== -1 && colonIdx < 60) {
        riskTitle = riskText.slice(0, colonIdx).trim();
        riskBody = riskText.slice(colonIdx + 1).trim();
      } else {
        // Fallback if no clear title/body separator
        riskTitle = riskText.slice(0, 50).trim();
        riskBody = riskText.slice(50).trim();
      }
      
      const isHigh = /high/i.test(riskTitle);
      const isAmb = /ambiguity|clarif|transition/i.test(riskTitle);
      const isMed = /medium/i.test(riskTitle);
      const isBlue = /data matching|system|tin|cross-referencing/i.test(riskTitle);

      const borderColor = isHigh ? RED : (isAmb || isMed) ? AMBER : (isBlue ? [37, 99, 235] : [59, 130, 246]) as [number, number, number];
      const bgColor: [number, number, number] = isHigh ? [254, 242, 242] : (isAmb || isMed) ? [255, 251, 235] : [239, 246, 255];
      
      const bodyLines = doc.splitTextToSize(riskBody, pageWidth - margin * 2 - 16);
      const cardH = Math.max(28, 12 + bodyLines.length * 5 + 8);
      
      if (cursorY + cardH > pageHeight - 25) { 
        doc.addPage(); 
        cursorY = 25; 
      }
      
      // Card background
      doc.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
      doc.roundedRect(margin, cursorY, pageWidth - margin * 2, cardH, 2, 2, 'F');
      
      // Thick left bar
      doc.setFillColor(borderColor[0], borderColor[1], borderColor[2]);
      doc.rect(margin, cursorY, 6, cardH, 'F');
      
      // Title
      doc.setFontSize(10.5); 
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(borderColor[0], borderColor[1], borderColor[2]);
      doc.text(riskTitle, margin + 10, cursorY + 9);
      
      // Body
      doc.setFont('helvetica', 'normal'); 
      doc.setFontSize(9.5);
      doc.setTextColor(40, 40, 40);
      doc.text(bodyLines, margin + 10, cursorY + 16);
      
      cursorY += cardH + 8;
      continue;
    }

    if (currentSection === 6) {
      if (/^\d+\./.test(line)) {
        const num = line.match(/^\d+/)?.[0] || "1";
        doc.setFillColor(ACCENT_GREEN[0], ACCENT_GREEN[1], ACCENT_GREEN[2]);
        doc.ellipse(margin + 4, cursorY - 1, 4, 4, 'F');
        doc.setTextColor(255);
        doc.setFontSize(8);
        doc.text(num, margin + 4, cursorY - 1, { align: "center" });
        
        cursorY = renderTaggedLine(line.replace(/^\d+\.\s*/, ""), cursorY, 10);
        continue;
      }
      
      if (line.toLowerCase().includes("complexity")) {
        const rating = line.match(/VERY HIGH|HIGH|MEDIUM|LOW/i)?.[0]?.toUpperCase() || "MEDIUM";
        const color = rating.includes("HIGH") ? RED : (rating === "LOW" ? GREEN : AMBER);
        
        doc.setFillColor(color[0], color[1], color[2]);
        doc.roundedRect(margin, cursorY, 40, 8, 2, 2, 'F');
        doc.setTextColor(255);
        doc.setFontSize(9);
        doc.text(`COMPLEXITY: ${rating}`, margin + 20, cursorY + 5.5, { align: "center" });
        cursorY += 15;
        continue;
      }
    }

    // Default line rendering
    cursorY = renderTaggedLine(line, cursorY);
    
    if (cursorY > pageHeight - 30) {
      doc.addPage();
      cursorY = 25;
      if (justStartedSection) {
        justStartedSection = false;
      } else {
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(currentSectionLabel + ' continued...', margin, 15);
      }
    }
  }

  // Final table flush
  if (inTable && tableHeaders.length > 0) {
    autoTable(doc, {
      startY: cursorY,
      head: [tableHeaders],
      body: tableRows,
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 3, lineColor: [200,220,210] },
      headStyles: {
        fillColor: PRIMARY_GREEN,
        textColor: [255,255,255],
        fontStyle: 'bold',
        fontSize: 9
      },
      alternateRowStyles: { fillColor: [248,250,248] },
      columnStyles: currentSection === 2 ? {
        0: { cellWidth: 28 },
        1: { cellWidth: 47 },
        2: { cellWidth: 47 },
        3: { cellWidth: 48 }
      } : currentSection === 3 ? {
        0: { cellWidth: 8 },
        1: { cellWidth: 25 },
        2: { cellWidth: 45 },
        3: { cellWidth: 25 },
        4: { cellWidth: 25 },
        5: { cellWidth: 42 }
      } : currentSection === 4 ? {
        0: { cellWidth: 8 },
        1: { cellWidth: 28 },
        2: { cellWidth: 35 },
        3: { cellWidth: 28 },
        4: { cellWidth: 71 }
      } : {},
    });
  }

  addFooter();
  doc.save(`TaxDiff_Analysis_${data.newForm}.pdf`);
}
